### ISSUE TITLE
Development Tracking

### ISSUE THREAD

**Issue by AmiroEmad** [MCrafterss/mcrafterss.github.io#1]
i am very tired i will continue this website in 1 or 2 days

**Comment by PocketKiller** [comment]
ill do it :+1:

**Comment by CraftingMania** [comment]
i will use github page maker

**Comment by PocketKiller** [comment]
no i want to disable it

**Comment by CraftingMania** [comment]
ok i will code without it

**Comment by PocketKiller** [comment]
please remove them all

**Comment by CraftingMania** [comment]
remove what part

**Comment by PocketKiller** [comment]
remove all automatic web generator from all repositories

**Comment by CraftingMania** [comment]
ok

**Comment by CraftingMania** [comment]
there is a small problem i dont know css

**Comment by PocketKiller** [comment]
I know CSS, but I am not profosonial on it. lets talk on gitter we're spamming notifications

**Comment by AmiroEmad** [comment]
please revert my last 2 commits

**Comment by AmiroEmad** [comment]
please revert my last 2 commits

**Comment by AmiroEmad** [comment]
finished coding the website
